### PR TITLE
Migrate to nuxtjs for easier development and modern ui

### PR DESCRIPTION
**Pull request by wesamdev**

### CODE REVIEW

**Comment by Bioblaze** [comment]
Can't accept this because the golang is gone, we need the golang for our api endpoints.

**Comment by wesamdev** [comment]
okay accept it and add go api endpoints

**Comment by Bioblaze** [comment]
need to make it so the compiled assets are put into the static folder for golang to host, you need to modify the dockerfile to build everything then store it there.
The api endpoints will be handled by golang.

**Comment by Bioblaze** [comment]
Can't use this, it needs to be moved into the static folder, and compiled. 
:( Nothing been moved in 3 weeks, closing ticket.

**Pull request closed without merging**
